trigger:
  none

pool: mypool

# parameters:
#   - name: env
#     type: string
#     displayName: enviromnent batana hai
#     default: dev
#     values:
#       - dev
#       - qa
#       - prod


steps:

- script: |
    python3 -m venv .venv
    source .venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Create venv and install dependencies"

- script: |
    pytest
  displayName: running pytest
  continueOnError: true

- script: |
    sudo apt-get update
    sudo apt-get install -y zip
  displayName: "Install zip tool"

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
    replaceExistingArchive: true
  displayName: Archive app

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: publish artifacts
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'my-sc-backend-pytodo'
    appType: 'webAppLinux'
    WebAppName: 'PyTodoBackendMonolith'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/drop.zip'
    RuntimeStack: 'PYTHON|3.13'
    StartupCommand: 'gunicorn -k uvicorn.workers.UvicornWorker app:app'
    DeploymentTypeLinux: 'oneDeploy'

